meta-facebook: harma: allow power sync to proceed
Update the service state check to ignore services in the
'active (exited)' state. Previously, any 'active' status would block
power good assertions/deassertions.

Change-Id: I73c7f628e53189e6d3da8ded0d93369770b4cb57
Signed-off-by: Peter Yin <peter.yin@quantatw.com>

diff --git a/meta-facebook/meta-harma/recipes-phosphor/state/phosphor-state-manager/host-force-poweroff b/meta-facebook/meta-harma/recipes-phosphor/state/phosphor-state-manager/host-force-poweroff
--- a/meta-facebook/meta-harma/recipes-phosphor/state/phosphor-state-manager/host-force-poweroff
+++ b/meta-facebook/meta-harma/recipes-phosphor/state/phosphor-state-manager/host-force-poweroff
@@ -2,5 +2,12 @@
 
 # shellcheck source=meta-facebook/meta-harma/recipes-phosphor/state/phosphor-state-manager/power-cmd
 source /usr/libexec/phosphor-state-manager/power-cmd
+trap '/usr/libexec/fb-common-functions set_gpio power-host-control 1' EXIT SIGTERM
 
-force_power_off
+if force_power_off; then
+    echo "Force power off command executed successfully."
+else
+    echo "Force power off command failed."
+    exit 1
+fi
+exit 0
